"""Agent connection helper — sets up integration between AgentHandover and execution agents.

Usage::

    agenthandover connect claude-code   # Register skills as /slash-commands
    agenthandover connect codex         # Generate AGENTS.md for Codex
    agenthandover connect openclaw      # Verify OpenClaw path and sync
    agenthandover connect mcp           # Show MCP config for any agent
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _get_kb_root() -> Path:
    """Resolve knowledge base root."""
    import platform
    if platform.system() == "Darwin":
        return Path.home() / "Library" / "Application Support" / "agenthandover" / "knowledge"
    return Path.home() / ".agenthandover" / "knowledge"


def _load_procedures() -> list[dict]:
    """Load all procedures from the knowledge base."""
    kb_root = _get_kb_root()
    proc_dir = kb_root / "procedures"
    if not proc_dir.is_dir():
        return []

    procedures = []
    for f in sorted(proc_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
            procedures.append(data)
        except (json.JSONDecodeError, OSError):
            pass
    return procedures


def connect_claude_code() -> None:
    """Set up Claude Code integration.

    Skills are already written by claude_skill_writer.py.
    This creates a meta-index skill and prints instructions.
    """
    skills_dir = Path.home() / ".claude" / "commands"
    skills_dir.mkdir(parents=True, exist_ok=True)

    procedures = _load_procedures()
    ready = [p for p in procedures if p.get("lifecycle_state") == "agent_ready"]

    # Generate index skill
    index_path = skills_dir / "agenthandover-list.md"
    lines = [
        "---",
        "description: List all AgentHandover procedures available for execution",
        "---",
        "",
        "# Available AgentHandover Procedures",
        "",
    ]

    if ready:
        for proc in ready:
            slug = proc.get("id", "?")
            title = proc.get("title", "Untitled")
            desc = proc.get("description", "")[:100]
            lines.append(f"- **{title}** (`/{slug}`): {desc}")
    else:
        lines.append("No agent-ready procedures yet. AgentHandover is still learning your workflows.")
        lines.append("")
        lines.append("Once procedures are approved, they will appear here as /slash-commands.")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by AgentHandover. Run `agenthandover connect claude-code` to refresh.*")

    index_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Claude Code integration ready.")
    print(f"  Skills directory: {skills_dir}")
    print(f"  Index: {index_path}")
    print(f"  Procedures available: {len(ready)}")
    print()
    if ready:
        print("Your procedures are available as /slash-commands:")
        for proc in ready:
            print(f"  /{proc.get('id', '?')} — {proc.get('title', '')}")
    print()
    print("For richer integration, add the MCP server:")
    print("  agenthandover connect mcp")


def connect_codex() -> None:
    """Generate AGENTS.md for Codex in the current directory."""
    procedures = _load_procedures()
    ready = [p for p in procedures if p.get("lifecycle_state") == "agent_ready"]

    lines = [
        "# Agent Instructions (AgentHandover)",
        "",
        "The following procedures were learned by observing the user's workflows.",
        "Each procedure includes steps, strategy, guardrails, and voice guidance.",
        "",
        "## Available Procedures",
        "",
    ]

    for proc in ready:
        slug = proc.get("id", "?")
        title = proc.get("title", "Untitled")
        desc = proc.get("description", "")
        strategy = proc.get("strategy", "")

        lines.append(f"### {title}")
        if desc:
            lines.append(f"{desc}")
            lines.append("")

        if strategy:
            lines.append(f"**Strategy**: {strategy}")
            lines.append("")

        steps = proc.get("steps", [])
        if steps:
            for s in steps:
                action = s.get("action", s.get("description", ""))
                lines.append(f"1. {action}")
            lines.append("")

        guardrails = proc.get("constraints", {}).get("guardrails", [])
        if guardrails:
            lines.append("**Guardrails:**")
            for g in guardrails:
                lines.append(f"- {g}")
            lines.append("")

        vp = proc.get("voice_profile", {})
        if vp and vp.get("formality"):
            lines.append(f"**Voice**: {vp['formality']} tone")
            lines.append("")

        lines.append("---")
        lines.append("")

    if not ready:
        lines.append("No agent-ready procedures yet. AgentHandover is still learning.")
        lines.append("")

    lines.append("*For real-time access, use the AgentHandover REST API at localhost:9477*")
    lines.append("*or the MCP server: `agenthandover serve-mcp`*")

    output = Path("AGENTS.md")
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Codex integration ready.")
    print(f"  Generated: {output.resolve()}")
    print(f"  Procedures: {len(ready)}")


def connect_openclaw() -> None:
    """Verify and configure OpenClaw integration."""
    import platform
    import tomllib

    openclaw_default = Path.home() / ".openclaw" / "workspace"

    # Read config to check custom path
    if platform.system() == "Darwin":
        config_path = Path.home() / "Library" / "Application Support" / "agenthandover" / "config.toml"
    else:
        config_path = Path.home() / ".config" / "agenthandover" / "config.toml"

    configured_path = openclaw_default
    if config_path.is_file():
        try:
            with open(config_path, "rb") as f:
                cfg = tomllib.load(f)
            wp = cfg.get("openclaw", {}).get("workspace_path", "")
            if wp:
                configured_path = Path(wp).expanduser()
        except Exception:
            pass

    sops_dir = configured_path / "memory" / "apprentice" / "sops"

    if sops_dir.is_dir():
        sop_count = len(list(sops_dir.glob("sop.*.md")))
        print(f"OpenClaw integration active.")
        print(f"  Workspace: {configured_path}")
        print(f"  SOPs directory: {sops_dir}")
        print(f"  Procedures synced: {sop_count}")
    elif configured_path.is_dir():
        print(f"OpenClaw workspace found at {configured_path}")
        print(f"  SOPs directory will be created when first procedure compiles.")
    else:
        print(f"OpenClaw workspace not found at {configured_path}")
        print()
        print("If OpenClaw is installed elsewhere, set the path in config.toml:")
        print()
        print("  [openclaw]")
        print('  workspace_path = "/path/to/openclaw/workspace"')


def connect_mcp() -> None:
    """Print MCP configuration for any MCP-compatible agent."""
    config = {
        "mcpServers": {
            "agenthandover": {
                "command": "agenthandover-mcp",
            }
        }
    }

    print("MCP Server configuration")
    print("========================")
    print()
    print("Add this to your agent's MCP settings:")
    print()
    print("For Claude Code (~/.claude/settings.json):")
    print(json.dumps(config, indent=2))
    print()
    print("For Cursor/Windsurf (settings.json > mcpServers):")
    print(json.dumps(config["mcpServers"]["agenthandover"], indent=2))
    print()
    print("Available MCP tools:")
    print("  - list_ready_procedures  — executable procedures only")
    print("  - list_all_procedures    — all procedures with lifecycle state")
    print("  - get_procedure(slug)    — full procedure with steps + strategy + voice")
    print("  - search_procedures(q)   — semantic search by meaning")
    print("  - get_user_profile       — user tools, hours, writing style")
    print()
    print("Start the server manually:")
    print("  agenthandover-mcp        # stdio transport (for agents)")
    print("  agenthandover-mcp --sse  # SSE transport (for HTTP clients)")


def main():
    """Entry point for `agenthandover connect` command."""
    if len(sys.argv) < 2:
        print("Usage: agenthandover connect <agent>")
        print()
        print("Agents:")
        print("  claude-code   Register skills as /slash-commands")
        print("  codex         Generate AGENTS.md for Codex")
        print("  openclaw      Verify OpenClaw path and sync status")
        print("  mcp           Show MCP config for any MCP-compatible agent")
        sys.exit(1)

    agent = sys.argv[1].lower().replace("_", "-")

    handlers = {
        "claude-code": connect_claude_code,
        "claude": connect_claude_code,
        "codex": connect_codex,
        "openclaw": connect_openclaw,
        "claw": connect_openclaw,
        "mcp": connect_mcp,
    }

    handler = handlers.get(agent)
    if handler is None:
        print(f"Unknown agent: {agent}")
        print(f"Available: {', '.join(handlers.keys())}")
        sys.exit(1)

    handler()


if __name__ == "__main__":
    main()
